OMODED_Shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path, re_path

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    # checkout,
    update_transaction_records,
    success,
    cart_list
)

app_name = 'shopping_cart'


urlpatterns = [
    re_path(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    path('order-summary/', order_details, name="order_summary"),
    path('success/', success, name='purchase_success'),
    re_path(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    re_path(r'^update-transaction/(?P<token>[-\w]+)/$', update_transaction_records, name='update_records'),
    path('view_cart/', cart_list, name='cart_list')
]

shop/urls.py
from django.urls import path, include
from .views import *
from accounts.views import my_profile

app_name = 'products'


urlpatterns = [
    path('', index, name='home'),
    path('collections/', CollectionsView.as_view(), name='collections'),
    path('search/', search, name='search'),
    path('collections/<slug:collection_slug>/', Collection.as_view(), name='collection'),
    path('collections/<slug:collection_slug>/product/<slug:good_slug>/', Good.as_view(), name='good'),
    path("account/register/", register_request, name="register"),
    path('account/login/', LoginRequest.as_view(), name='login'),
    path('account/password_reset/', ResetRequest.as_view(), name='password_reset'),
    path('account/profile/', my_profile, name='profile'),
    path('cart/', include('cart.urls')),
    path('pages/conventions_2022/', conventions, name='conventions'),
    path('pages/collaborations/', collaborations, name='collaborations'),
    path('pages/retailers/', retailers, name='retailers'),
    path('pages/about/', about, name='about'),
    path('community/faq/', faq, name='faq'),

]

urlpatterns += [
    path('account/', include('django.contrib.auth.urls')),
]

cart/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from accounts.models import Profile
from shop.models import Goods


class OrderItem(models.Model):
    product = models.OneToOneField(Goods, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.product.cost for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)


class Transaction(models.Model):
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
    token = models.CharField(max_length=120)
    order_id = models.CharField(max_length=120)
    amount = models.DecimalField(max_digits=100, decimal_places=2)
    success = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return self.order_id

    class Meta:
        ordering = ['-timestamp']

cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from accounts.models import Profile
from shop.models import Goods
from django.http import JsonResponse
from cart.extras import generate_order_id
from cart.models import OrderItem, Order, Transaction

import datetime
import stripe


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Profile, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def cart_list(request):
    ctx = {}
    user_profile = get_object_or_404(Profile, user=request.user)
    cart_orders = Order.objects.filter(owner=user_profile, is_ordered=False)

    ctx['cart_orders'] = cart_orders

    return render(request, "shop/cart_list.html", context=ctx)


@login_required()
def add_to_cart(request, **kwargs):
    user_profile = get_object_or_404(Profile, user=request.user)
    product = Goods.objects.filter(id=kwargs.get('item_id', "")).first()
    order_item, status = OrderItem.objects.get_or_create(product=product)
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        user_order.ref_code = generate_order_id()
        user_order.save()

    messages.info(request, "item added to cart")
    return redirect('/')


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Item has been deleted")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/order_summary.html', context)


# @login_required()
# def checkout(request, **kwargs):
#     client_token = generate_client_token()
#     existing_order = get_user_pending_order(request)
#     publishKey = settings.STRIPE_PUBLISHABLE_KEY
#     if request.method == 'POST':
#         token = request.POST.get('stripeToken', False)
#         if token:
#             try:
#                 charge = stripe.Charge.create(
#                     amount=100 * existing_order.get_cart_total(),
#                     currency='usd',
#                     description='Example charge',
#                     source=token,
#                 )
#
#                 return redirect(reverse('shopping_cart:update_records',
#                                         kwargs={
#                                             'token': token
#                                         })
#                                 )
#             except stripe.CardError as e:
#                 message.info(request, "Your card has been declined.")
#         else:
#             result = transact({
#                 'amount': existing_order.get_cart_total(),
#                 'payment_method_nonce': request.POST['payment_method_nonce'],
#                 'options': {
#                     "submit_for_settlement": True
#                 }
#             })
#
#             if result.is_success or result.transaction:
#                 return redirect(reverse('shopping_cart:update_records',
#                                         kwargs={
#                                             'token': result.transaction.id
#                                         })
#                                 )
#             else:
#                 for x in result.errors.deep_errors:
#                     messages.info(request, x)
#                 return redirect(reverse('shopping_cart:checkout'))
#
#     context = {
#         'order': existing_order,
#         'client_token': client_token,
#         'STRIPE_PUBLISHABLE_KEY': publishKey
#     }
#
#     return render(request, 'shopping_cart/checkout.html', context)


@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered = True
    order_to_purchase.date_ordered = datetime.datetime.now()
    order_to_purchase.save()

    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Profile, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()

    # create a transaction
    transaction = Transaction(profile=request.user.profile,
                              token=token,
                              order_id=order_to_purchase.id,
                              amount=order_to_purchase.get_cart_total(),
                              success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()

    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Thank you! Your purchase was successful!")
    return redirect(reverse('accounts:my_profile'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/purchase_success.html')

templates/inc/_cart.html
{% for order in found_cart_orders_ajax %}
    {% for item in order.get_cart_items %}
        <li><a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a></li>
    {% endfor %}
{% endfor %}

templates/inc/_footer.html
{% load static %}
<footer>
	<div class="footer">
		<div class="container">
			<div class="row">
				<div class="foot-item col-md-3">
					<div class="foot_item_links">
					    <div class="h3 footerHeader">Info</div>
					    <ul class="footer-link-content">
					        <li>
					            <a href="/pages/about">About UWUDEAD</a>
					        </li>
					        <li>
					            <a href="/community/faq">FAQ</a>
					        </li>
					    </ul>
					</div>
				</div>

				<div class="foot-item col-md-3">
					<div class="foot_item_media">
						<div class="h3 footerHeader">Social Media</div>
						<ul class="logo_of_media">
							<li><a href="#" class='social-media-link facebook'><i class="fa fa-facebook fa2" id='fb' aria-hidden="true"></i></a></li>
							<li><a href="#" class='social-media-link twitter'><i class="fa fa-twitter" id='twi' aria-hidden="true"></i></a></li>
							<li><a href="#" class='social-media-link instagram'><i class="fa fa-instagram fa2" id='inst' aria-hidden="true"></i></a></li>
						</ul>
					</div>
				</div>

				<div class="foot-item col-md-3">
					<div class="foot_item_news">
					    <div class="h3 footerHeader">Newsletter</div>
					    <form method="post" action="/contact#newsletter-footer_form" id="newsletter-footer_form" accept-charset="UTF-8" class="contact-form"><input type="hidden" name="form_type" value="customer"><input type="hidden" name="utf8" value="✓">
					        <div class="input-group">
					            <input type="email" value="" placeholder="email@example.com" name="contact[email]" id="Email" class="input-group-field footer-email-input" aria-label="email@example.com">
					            <input type="hidden" name="contact[tags]" value="newsletter">
					            <span>
					                    <input type="submit" class="btn footer-email-submit" name="subscribe" id="subscribe" value="JOIN US">
					            </span>
					        </div>
					    </form>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

templates/inc/_header.html
{% load static %}
<header class="header">
        <nav>
            <div class="header-icon">
                <ul class="header-links">
                    <div class="toggle-btnSearch" onclick="openMenuSearch()">
                        <li class="search-icon"></li>
                    </div>
                    <div id="sidebarSearch">
                        <ul>
                            <li>Lookin' for something?</li>
                            <li class="palo4ka-lol"></li>
                            <li>
                                <span>
                                    <form action="/search/" method="get">
                                        {% csrf_token %}
                                        <input id="user-input" type="text" name="q" placeholder="  Search our store" class="search" autocomplete="off" aria-label="  Search our store">
                                        <button type="submit" class="submit-btnSearch">
                                            <i id="search-icon" class="submit-btnSearchIcon"></i>
                                        </button>
                                    </form>
                                </span>
                            </li>
                            <li class="cancel-btnSearch" onclick="openMenuSearch()"></li>
                            <li id="replaceable-content">
                                {% include 'inc/_search.html' %}
                            </li>
                        </ul>
                    </div>
                    {% if user.is_authenticated %}
                        <div class="toggle-btnUser" onclick="window.location.href = '{% url 'products:profile' %}'">
                            <li class="user-icon"></li>
                        </div>
                    {% else %}
                        <div class="toggle-btnUser" onclick="window.location.href = '{% url 'products:login' %}?next={% firstof request.path '/' %}'">
                            <li class="user-icon"></li>
                        </div>
{#                        <div class="toggle-btnUser" onclick="openMenuUser()">#}
{#                            <li class="user-icon"></li>#}
{#                        </div>#}
{#                        <div id="sidebarUser">#}
{#                            <ul>#}
{#                                <li>Login</li>#}
{#                                <li class="palo4ka-lol-2"></li>#}
{#                                <li>#}
{#                                    <div class="emailAndPassword">#}
{#                                        <span>#}
{#                                            <input type="email" name="q" placeholder="  Email" class="emailUser" autocomplete="off">#}
{#                                            <input type="password" name="q" placeholder="  Password" class="passwordUser" autocomplete="off">#}
{#                                            <input type="submit" class="SignIn" value="Sign In">#}
{#                                        </span>#}
{#                                    </div>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a class="UserLinks-createAccount" href="/account/register">Create account</a>#}
{#                                </li>#}
{#                                <li>#}
{#                                    <a class="UserLinks-ForgotYourPassword" href="#">Forgot your password?</a>#}
{#                                </li>#}
{#                                <li class="cancel-btnUser" onclick="openMenuUser()"></li>#}
{#                            </ul>#}
{#                        </div>#}
                    {% endif %}
                    <div class="toggle-btnCart" id="cart_icon" onclick="openMenuCart()">
                        <li class="buy-icon"></li>
                    </div>
                    <div id="sidebarCart">
                        <ul>
                            <li>Shopping Cart</li>
                            <li class="palo4ka-lol-3"></li>

                            <li class="cancel-btnCart" onclick="openMenuCart()"></li>
                            {% if user.is_authenticated %}
                                {% for order in cart_orders %}
                                    {% for item in order.get_cart_items %}
                                        <div class="cartItem">
                                            <p>{{ item }}</p>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </ul>
            </div>
            <h1 class="logo">
                <a href="/"><img src="{% static 'img/logo.jpg' %}" width="72" height="69"></a>
            </h1>
            <ul class="nav">
                <li class="nav-item">
                    <a class="nav-link" href="/collections">
                    <div>
                        <span>COLLECTIONS</span>
                        <span class="icon-dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.5" height="22.5" viewBox="5 -7 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </span>
                    </div>
                    </a>
                    <ul class="site-dropDownMenuCollections">
                        <li>
                            <a href="/collections/omori" class="site-nav__link">OMORI</a><br>
                        </li>
                        <li>
                            <a href="/collections/hololive-en" class="site-nav__link">HOLOLIVE EN</a>
                        </li>
                        <li>
                            <a href="/collections/doki-doki-literature-club" class="site-nav__link">DDLC!</a>
                        </li>
                        <li>
                            <a href="/collections/hatsune-miku" class="site-nav__link">HATSUNE MIKU</a>
                        </li>
                        <li>
                            <a href="/collections/original" class="site-nav__link">ORIGINAL</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/collections/apparel">
                        <div>
                            <span>APPAREL</span>
                            <span class="icon-dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.5" height="22.5" viewBox="5 -7 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </span>
                        </div>
                    </a>
                    <ul class="site-dropDownMenuApparel">
                        <li>
                            <a href="/collections/shirts" class="site-nav__link">Shirts</a>
                        </li>
                        <li>
                            <a href="/collections/sweaters" class="site-nav__link">Sweaters</a>
                        </li>
                        <li>
                            <a href="/collections/jackets" class="site-nav__link">Jackets &amp; Hoodies</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/collections/accessories">
                        <div>
                            <span>ACCESSORIES</span>
                            <span class="icon-dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.5" height="22.5" viewBox="5 -7 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </span>
                        </div>
                    </a>
                    <ul class="site-dropDownMenuAccessories">
                        <li>
                            <a href="/collections/plushies" class="site-nav__link">Plushies</a>
                        </li>
                        <li>
                            <a href="/collections/pins" class="site-nav__link">Pins</a>
                        </li>
                        <li>
                            <a href="/collections/stickers" class="site-nav__link">Stickers</a>
                        </li>
                        <li>
                            <a href="/collections/skate-decks" class="site-nav__link">Skate Decks</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/collections/printed-matter">
                        <div>
                            <span>PRINTED MATTER</span>
                            <span class="icon-dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.5" height="22.5" viewBox="5 -7 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </span>
                        </div>
                    </a>
                    <ul class="site-dropDownMenuPrintedMatter">
                        <li>
                            <a href="/collections/books" class="site-nav__link">Books &amp; Booklets</a>
                        </li>
                        <li>
                            <a href="/collections/posters-prints" class="site-nav__link">Posters &amp; Prints</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        <div>
                            <span>SHOWCASE</span>
                            <span class="icon-dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.5" height="22.5" viewBox="5 -7 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </span>
                        </div>
                    </a>
                    <ul class="site-dropDownMenuShowcase">
                        <li>
                            <a href="/pages/conventions_2022" class="site-nav__link">CONVENTIONS 2022</a>
                        </li>
                        <li>
                            <a href="/pages/collaborations" class="site-nav__link">COLLABORATIONS</a><br>
                        </li>
                        <li>
                            <a href="/pages/retailers" class="site-nav__link">RETAILERS</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/">
                        <div>
                            <span>INFO</span>
                            <span class="icon-dropdown">
                                                <svg xmlns="http://www.w3.org/2000/svg" width="22.5" height="22.5" viewBox="5 -7 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-down"><polyline points="6 9 12 15 18 9"></polyline></svg>
                        </span>
                        </div>
                    </a>
                    <ul class="site-dropDownMenuInfo">
                        <li>
                            <a href="/pages/about" class="site-nav__link">About UWUDEAD</a>
                        </li>
                        <li>
                            <a href="/community/faq" class="site-nav__link">FAQ</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>

templates/inc/_search.html
{% if found_goods_ajax %}
        {% for good in found_goods_ajax %}
            <div class="ajx-search-result">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-4">

                            <div class="ajx-search_img">
                                <a href="{{ good.get_absolute_url }}">
                                    <img class='ajx-search-result_img' src="{{ good.photo1.url }}" alt="">
                                </a>
                            </div>
                        </div>

                        <div class="col-xs-8">
                            <div class="ajx-search-name-price">
                                <a class="ajx-search-name" href="{{ good.get_absolute_url }}">{{ good.name }}</a>
                                <p class="ajx-search-price">{{ good.cost }}$</p>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
            <hr>
        {% endfor %}
{% endif %}